name: Sync GitLab Activity to GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Exécute chaque dimanche à minuit

jobs:
  sync_activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch and Process GitLab Activity
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_USER_ID: ${{ secrets.GITLAB_USER_ID }}
        run: python fetch_gitlab_activity.py

      - name: Commit and Push changes
        run: |
          git config --global user.email "hydris.bessa@gmail.com"
          git config --global user.name "GitHub Action"
          git add ACTIVITY.md
          git commit -m "Mise à jour hebdomadaire de l'activité GitLab" || echo "No changes to commit"
          git push
